# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afe2246763eab8aac7e3e0b222aeb78a16219b9ec18701a092bd40810cd0427eb4e65ff4d5747441cdacb9b9ad59b19a656fc548ccbf343112781db649b46338

test:
  secret_key_base: 281031b764187dc6b9a92988465091eae3d6c7b3fdbcf7dfa3c456e3a93eeda4f86ceb79d1bd45dfdaf5930ec38e21f74610d397bc885397db84dac842d9fa7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
